import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { signInWithPopup } from "firebase/auth";
import { auth, provider } from "@/feature/firebase";
import { Typography } from "@mui/material";
import FavoriteIcon from "@mui/icons-material/Favorite";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div 
          onClick={() => {
            signInWithPopup(auth, provider)
              .then((result) => console.log(result.user))
              .catch((error) => alert(error.message));
          }}
        >
          hello how are you today
        </div>
        <Typography variant="h4" component="h1">今日は良い天気ですね</Typography>
        <FavoriteIcon />
      </main>
    </>
  );
}
